apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld  # Ensure this matches the app label in the Deployment
  ports:
    - protocol: TCP
      port: 80         # Internal service port
      targetPort: 80   # Port inside the container
      nodePort: 30080  # Port exposed externally on the node
  type: NodePort  # Expose the service using NodePort
