Vagrant.configure(2) do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.box_version = "11.20240905.1"
        # config.vm.box_url = REDACTED
    config.vm.define "sbarrageS" do |control|
        control.vm.hostname = "sbarrageS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "sbarrageS"]
            v.memory = 2048
            v.cpus = 1
        end
        control.vm.provision "file", source: "./conf.yaml", destination: "/tmp/config.yaml"
        # control.vm.provision "file", source: "./shell.conf/controller.sh", destination: "/tmp/entrypoint.sh"
        control.vm.provision "shell", path: "./entrypoint.sh"
    end
end